import Head from 'next/head';
import Image from 'next/image';
import {ProductContext} from "../context/ProductContext";
import {useContext} from "react";
import Product from "../components/Product";

export default function Home({products}) {
	const {onAdd, cartItems} = useContext(ProductContext);
	// console.log(onAdd);
	console.log(products);
	console.log(cartItems);

	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main>
				<h1 className="text-3xl font-bold underline"> Hello world! </h1>
				<div className='flex flex-col md:flex-row items-center justify-center'>
					<ul className='flex flex-col md:flex-row'>
						{products.map((product) => (
							<Product key={product.id} product={product} onAdd={onAdd} src={product.main_img.link}></Product>
						))}
					</ul>
				</div>



				{/*<p>{initialState}</p>*/}
			</main>


		</div>
	);
}
export const getStaticProps = async () => {
	const res = await fetch(`https://electronis-api.herokuapp.com/api/phones`);
	const products = await res.json();

	return {
		props: {
			products,
		},
	};
};
