import Head from 'next/head';
import Image from 'next/image';
import {ProductContext} from "../context/ProductContext";
import {useContext} from "react";
import Product from "../components/Product";

export default function Home() {
	const {onAdd, products, cartItems} = useContext(ProductContext);
	// console.log(onAdd);
	console.log(products);
	console.log(cartItems);

	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main>
				<h1 className="text-3xl font-bold underline"> Hello world! </h1>
				<ul>
					{products.map((product) => (
						<Product key={product.id} product={product} onAdd={onAdd}></Product>
					))}
				</ul>


				{/*<p>{initialState}</p>*/}
			</main>


		</div>
	);
}
