import Head from 'next/head';
import Image from 'next/image';
import {ProductContext} from "../context/ProductContext";
import {useContext} from "react";
// import Slider from "react-slick";
import Product from "../components/Product";
import Link from "next/link";
import FilterByPrice from "../components/filters/FilterByPrice";
import FilterByBrand from "../components/filters/FilterByBrand";
import SliderComponent from "../components/SliderComponet";
import Photo from '../assets/1.jpg'

export default function Home({products}) {
	const {onAdd, cartItems,} = useContext(ProductContext);
	// console.log(onAdd);
	// console.log(products);
	// console.log(cartItems);

	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main className="flex font-dosis md:mx-0 lg:mx-60 flex-col md:flex-row">
				<section className=" basis-1 lg:basis-1/5">
					<div className='hidden lg:block bg-pink-300'>
					<ul>
						<li>test</li>
						<li>test</li>
						<li>test</li>
						<li>test</li>
						<li>test</li>
					</ul>
					</div>
				</section>
				<section className="lg:basis-4/5 bg-green-200">


					<div className='w-full h-96'>
						{/*<SliderComponent />*/}
						<img src='https://images.unsplash.com/photo-1645474906518-6542b42f9bef?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxMHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60'
							 alt="" className='w-full object-fit h-96'/>
					</div>
				</section>
			</main>


		</div>
	);
}
export const getStaticProps = async () => {
	const res = await fetch(`https://electronis-api.herokuapp.com/api/phones`);
	const products = await res.json();

	return {
		props: {
			products,
		},
	};
};
